# Exported from Render on 2024-08-31T05:20:33Z
databases:
- name: render-test-db
  databaseName: render_test_db_uus4
  user: render_test_db_uus4_user
  plan: free
  region: virginia
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: render-test
  runtime: node
  repo: https://github.com/TheHiddenHour/render-test
  plan: free
  region: virginia
  buildCommand: npm install; npm run build
  startCommand: node build/index.js
version: "1"
